import { createElement } from 'lwc';
import Neighborhood_card_intro from 'c/neighborhood_card_intro';

describe('c-neighborhood-card-intro', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-neighborhood-card-intro', {
            is: Neighborhood_card_intro
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});